name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        
        **Looking for help?** For support questions, please use [Bazel slack](https://slack.bazel.build).
        
        Note that the maintainers prioritize bug reports from our Open Source Support customers.
        Sign up at [aspect.dev](https://www.aspect.dev/services#support).
        We have limited "hobby time" and are unlikely to fix other bugs.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: Please tell us about your environment
      value: |
        Development (host) and target OS/architectures:

        Output of `bazel --version`:

        Version of the Aspect rules, or other relevant rules from your
        `WORKSPACE` or `MODULE.bazel` file:

        Language(s) and/or frameworks involved:
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Your bug is more likely to be resolved if you provide exact steps to reproduce, and if possible a minimal demo of the problem.
      render: shell

  - type: textarea
    id: other
    attributes:
      label: Any other information?
      description: |
        (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, things you've tried, links for us to have context, eg. stackoverflow, gitter, etc)
  
  - type: markdown
    attributes:
      value: "## _Need help?_"

  - type: markdown
    attributes:
      value: |
        Community support for Aspect Bazel rules is available on [Bazel Slack](slack.bazel.build)
           - [#javascript](https://bazelbuild.slack.com/archives/CEZUUKQ6P) channel for [rules_js](https://github.com/aspect-build/rules_js) & derivate JavaScript rules
           - [#python](https://bazelbuild.slack.com/archives/CA306CEV6) channel for [rules_py](https://github.com/aspect-build/rules_py)
           - [#cc](https://bazelbuild.slack.com/archives/CGA9QFQ8H) channel for [gcc-toolchain](https://github.com/aspect-build/gcc-toolchain)
           - [#aspect-dev](https://bazelbuild.slack.com/archives/C04281DTLH0) channel for [Aspect CLI](https://github.com/aspect-build/aspect-cli) & general support

  - type: markdown
    attributes:
      value: Commercial support is provided by https://aspect.dev.

  - type: markdown
    attributes:
      value: "## _Slow CI/CD with Bazel?_"

  - type: markdown
    attributes:
      value: Accelerate your CI/CD pipeline with [Aspect Workflows](https://www.aspect.build/workflows) - the efficient and reliable build, test, and CI/CD platform for Bazel.

  - type: markdown
    attributes:
      value: Book a [demo](https://www.aspect.build/book-a-demo) today to experience lightning-fast builds and streamline your development process.
