name: Feature Request
description: Suggest an idea for this project
title: "[FR]: "
labels: ["enhancement"]
body:

  - type: markdown
    attributes:
      value: |
        Before filing, consider whether there's another place this feature might be better layered.
        Consider that the tool being invoked by Bazel might be broken,
        or that your specific, proximate problem has a more general, ultimate solution.

  - type: textarea
    id: current
    attributes:
      label: What is the current behavior?
      description: To make sure we agree on this.

  - type: textarea
    id: idea
    attributes:
      label: Describe the feature
      description: What is the motivation / use case for changing the behavior?
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## _Need help?_"

  - type: markdown
    attributes:
      value: |
        Community support for Aspect oBazel rules on [Bazel Slack](slack.bazel.build)
           - [#javascript](https://bazelbuild.slack.com/archives/CEZUUKQ6P) channel for [rules_js](https://github.com/aspect-build/rules_js) & derivate JavaScript rules
           - [#python](https://bazelbuild.slack.com/archives/CA306CEV6) channel for [rules_py](https://github.com/aspect-build/rules_py)
           - [#cc](https://bazelbuild.slack.com/archives/CGA9QFQ8H) channel for [gcc-toolchain](https://github.com/aspect-build/gcc-toolchain)
           - [#aspect-dev](https://bazelbuild.slack.com/archives/C04281DTLH0) chnanel for [Aspect CLI](https://github.com/aspect-build/aspect-cli) & general support

  - type: markdown
    attributes:
      value: Commercial support provided by https://aspect.dev.

  - type: markdown
    attributes:
      value: "## _Slow CI/CD with Bazel?_"

  - type: markdown
    attributes:
      value: Accelerate your CI/CD pipeline with [Aspect Workflows](https://www.aspect.build/workflows) - the efficient and reliable build, test, and CI/CD platform for Bazel.

  - type: markdown
    attributes:
      value: Book a demo today to experience lightning-fast builds and streamline your development process.
